name: Run ML Pipeline

# Trigger the workflow on every push to the main branch
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows you to run this manually from the Actions tab

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code onto the server
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Install dependencies
      - name: Install libraries
        run: |
          pip install -r requirements.txt

      # 4. Run your main script
      - name: Execute Pipeline
        run: python main.py

      # 5. Upload the results (Model and Figures) so you can download them
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: experiment-results
          path: |
            perovskite_rf_model.pkl
            *.png
            *.pdf
